### ISSUE TITLE
error with lv_examples.h in arduino

### ISSUE THREAD

**Issue by fairytail655** [lvgl/lv_demos#114]
After including library "lv_examples"(v8.1.0) in Arduino IDE, I compiled my stretch, the following error occurred.
```
fatal error: lv_examples.h: No such file or directory
```
I think there is a bug in file "library.properties". "includes=lv_examples.h" should be replaced with "includes=lv_demo.h".

**Comment by kisvegabor** [comment]
Thanks, I fixed it in master: https://github.com/lvgl/lv_demos/commit/4124ff63d032d24848de1230037034b66d56bd60
