### ISSUE TITLE
For which version of LVGL are these demos?

### ISSUE THREAD

**Issue by SinglWolf** [lvgl/lv_demos#119]
As far as I understood, reading the official documentation, the ``create_cont()`` function does not exist in the current version of the LVGL, it has been canceled?

![2021-09-07_07-52-57](https://user-images.githubusercontent.com/32172969/132277178-e9c5bb27-7c11-4d7d-ace6-bc6de877b794.png)

**Comment by embeddedt** [comment]
These are helper functions defined [at the bottom of `lv_demo_music_main.c`](https://github.com/lvgl/lv_demos/blob/8aa1af153734fb0efe145525778f55f619a42467/src/lv_demo_music/lv_demo_music_main.c#L338).

**Comment by SinglWolf** [comment]
> Это вспомогательные функции, определенные [в нижней части `lv_demo_music_main.c`](https://github.com/lvgl/lv_demos/blob/8aa1af153734fb0efe145525778f55f619a42467/src/lv_demo_music/lv_demo_music_main.c#L338).

OMG, I'm already confused about these versions, thanks.
