### ISSUE TITLE
#132 breaks build

### ISSUE THREAD

**Issue by higaski** [lvgl/lv_demos#134]
The latest commit which merged the PR #132 broke my build. It removed font declarations needed later in the file.

```sh
lv_demo_benchmark.c:404:44: error: ‘lv_font_montserrat_12_compr_az’ undeclared (first use in this function); did you mean ‘lv_font_montserrat_12_subpx’?
  404 |     lv_style_set_text_font(&style_common, &lv_font_montserrat_12_compr_az);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            lv_font_montserrat_12_subpx
```

**Comment by liukangcc** [comment]
Sorry, I improved the code, you can review the PR.

**Comment by kisvegabor** [comment]
True, see https://github.com/lvgl/lv_demos/pull/132#issuecomment-970145414

**Comment by mz8023yt** [comment]
中文：这个问题需要在 lv_conf.h 文件中，将 LV_FONT_MONTSERRAT_12 宏空的值从 0 修改为 1。
English：This problem requires changing the LV_FONT_MONTSERRAT_12 macro value from 0 to 1 in the lv_conf.h file.
